name: Caller backendTesting
on:
  push:
    branches:
      - Dev
      - Test
      - Prod
  pull_request:
    branches:
      - Dev
      - Test
      - Prod

jobs:
  ReuseableJobForCICD:
    uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/backend-testing.yml@main
