name: Caller CI/CD Workflow

on:
  push:
    branches:
      - Dev
      - Test
      - Prod
  pull_request:
    branches:
      - Dev
      - Test
      - Prod

jobs:
  ReuseableJobForCICD:
    uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/cicd.yml@main
    with:
      pom_path: 'pom.xml'
      service: 'orders-service'
      target: ${{ github.ref_name }}
    secrets: inherit
